import { ProductFeature } from '../types/game';

export const INITIAL_FEATURES: ProductFeature[] = [
  {
    id: 'f1',
    name: 'Core Product MVP',
    description: 'Build the basic working product',
    tier: 1,
    status: 'AVAILABLE',
    progress: 0,
    weeksToComplete: 3,
    qualityBonus: 15,
    revenueMultiplier: 1.2,
    churnReduction: 0,
    userBonus: 0,
    prerequisiteIds: [],
    active: false,
  },
  {
    id: 'f2',
    name: 'User Onboarding Flow',
    description: 'Smooth onboarding reduces churn by 3%',
    tier: 1,
    status: 'LOCKED',
    progress: 0,
    weeksToComplete: 4,
    qualityBonus: 10,
    revenueMultiplier: 1.0,
    churnReduction: 0.03,
    userBonus: 0,
    prerequisiteIds: ['f1'],
    active: false,
  },
  {
    id: 'f3',
    name: 'Analytics Dashboard',
    description: 'Users love data insights — boosts revenue',
    tier: 2,
    status: 'LOCKED',
    progress: 0,
    weeksToComplete: 5,
    qualityBonus: 12,
    revenueMultiplier: 1.15,
    churnReduction: 0,
    userBonus: 0,
    prerequisiteIds: ['f1'],
    active: false,
  },
  {
    id: 'f4',
    name: 'API Integrations',
    description: 'Opens the enterprise market segment',
    tier: 2,
    status: 'LOCKED',
    progress: 0,
    weeksToComplete: 6,
    qualityBonus: 8,
    revenueMultiplier: 1.25,
    churnReduction: 0,
    userBonus: 0,
    prerequisiteIds: ['f1'],
    active: false,
  },
  {
    id: 'f5',
    name: 'Mobile App',
    description: 'Doubles your addressable market',
    tier: 2,
    status: 'LOCKED',
    progress: 0,
    weeksToComplete: 8,
    qualityBonus: 15,
    revenueMultiplier: 1.0,
    churnReduction: 0,
    userBonus: 500,
    prerequisiteIds: ['f2'],
    active: false,
  },
  {
    id: 'f6',
    name: 'AI Recommendations',
    description: 'Flagship differentiator — massive revenue boost',
    tier: 3,
    status: 'LOCKED',
    progress: 0,
    weeksToComplete: 10,
    qualityBonus: 20,
    revenueMultiplier: 1.4,
    churnReduction: 0,
    userBonus: 0,
    prerequisiteIds: ['f3', 'f4'],
    active: false,
  },
];